name: Scott Gardner
title: Scott Gardner
description: iOS App Architect / Developer, Author & Apple Certified Trainer
theme: jekyll-theme-cayman
permalink: /:name
plugins:
    - jekyll-feed
    - jekyll-redirect-from
defaults:
    -
        scope:
            path: ""
            type: posts
        values:
            layout: default
            author: Scott Gardner
            permalink: /:title
owner: 
    name: Scott Gardner
    avatar: https://avatars2.githubusercontent.com/u/1337867
    twitter: scotteg
    linkedin: scotteg